server:
  port: 8083

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: citizen-service
          uri: lb://citizen-service
          predicates:
            - Path=/api/v1/**
        - id: Vaccination-Center
          uri: lb://Vaccination-Center
          predicates:
            - Path=/api/v11/centers/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v12/notifications/**